### ISSUE TITLE
OfflineAudioContext Not Implemented in Safari

### ISSUE THREAD

**Issue by gregzanch** [gregzanch/cram#58]
Impulses responses do not work in Safari due to the lack of an `OfflineAudioContext`

**Comment by jcbreton** [comment]
I looked into this, and this might be what Safari returns when there is an issue with the arguments used to initialize an `OfflineAudioContext`. We could look into browser checking in case Safari requires specific arguments?

**Comment by gregzanch** [comment]
Right on @jcbreton

**Comment by gregzanch** [comment]
fixed the safari issue in #59
